language: julia
dist: trusty
julia:
  - 0.4
  - 0.5
  # - nightly # nightly is not worth testing for now - it fails immediately on 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'include("install.jl"); include("runtests.jl")'
