language: julia
dist: trusty
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'include("install.jl"); include("runtests.jl")'
